name: "Build'n'Test"
on: [push, pull_request]

jobs:
  main:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
