name: "BuildTestDocker"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildtest:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
      - name: Push to DockerHub
#        if: github.ref == "refs/heads/$default-branch" && github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker push karfau/plantuml
