name: "Build'n'Test"
on: [push, pull_request]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
 docker:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build-docker.sh
      - run: ./test-docker.sh
