name: "BuildTestDocker"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildtest:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # tag=v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
      - name: "Fail if git detects changes"
        run: git add --verbose --all && git diff HEAD --exit-code
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # tag=v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: docker push --all-tags karfau/plantuml
