name: "BuildTestDocker"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildtest:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # renovate: tag=v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
      - name: "Fail if git detects changes"
        run: git add --verbose --all && git diff HEAD --exit-code
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7 # renovate: tag=v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: docker push --all-tags karfau/plantuml
