name: "BuildTestDocker"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildtest:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # renovate: tag=v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
      - name: "Fail if git detects changes"
        run: git add --verbose --all && git diff HEAD --exit-code
      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to DockerHub
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: docker push --all-tags karfau/plantuml
