name: "Build'n'Test"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    name: "BuildAndTest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - run: ./build-docker.sh
      - run: ./test-docker.sh
